env:
  global:
  - secure: WNUejX/NpwVT00RhHrvBsS/CNFPvj0MSAGbXMsEhVHK+smYM8lLU7V9ge1K2T8FcQuNxbYa2sT22nhx0eB9N2FEasJsa5C5Y/UD2BjzQUpsRu2PYOYnFukUc55iEFbSFyLw14UYoLufr4KHhM1VpD0EMNFP+uoXe04s+dmO/OSWoSWEPfs2ux/KmYRnR/kwDeKJoaIOckgVHlvpK4Ebwn2Gd5bX5K/Y72+OpSXztIC7u+xol5Wcv/mK7gIek71XTQLqJzazXLy6dD8Hyk6DqA2XY5pO2mxotbh5lEXlgtgZgv3JP99JVojNcMDtVzxPKwZr+PU4Hb1jsmEB2gCi1E86ht1AejmvII4Ta2WkUQKMQGRiNEp6IwgusZ5IVMVz6PkAtT+VLZbm//v8w/E3kwjYII2LAXBVDx4dYikoIqSY2HfY8AqvIBpUORhpxjmrEcR35OgCtdM0+iCYZSoe/F/6ARCzyM642wOZVuSKTuuTlRj1IoBxE8LjGNQi8UYu3VxudQyEGRgwkDrNN/q6UbFX9xLTcNESW8jP++vIKnk9rbD05+usD8wzKkijOK69UUkzPEmeFPnLe80Ds4akTzXTSvHMTYDB44cnpPbb7laXv2qbCF4J7DUDDJav/ptSYtj9FsqznvvsFSqA6G5GuN/Gw4FHOmRFcKB1poJtaf5s=
  - secure: mjpUXutxGeeXXJlSImet/1kTmLvpUnZaGn5ZowtgbGGEqUcsD3PMdpByjlzR4+gnz0xHwiBsJnZ9E5SFxBsLRx2kDMH6mtgSD2XFpXednM4MiNpII50icTct3rQ+5+Vl+nkitOO7C3/4CGVlDMnZAe0CPak/FKPYH4Q2K93l1Ncq1imqCtotHBZR/+z7XPU1Y+Z/5+QMP19cf5QCcLQRvVm0G5Liom/GDQJ8lukUMjutIpTGtpWZd9Z/ENUaUhp+A7UU3TK6DH70onStQxjLZ8RovNLuoO8/V7ag/AsAEQsIikCmj7w8WjNXRZsR0p+Uf2F4crswaLecPcRt9P/3EwTlIIRg9UinsbNaBcu2878P5O27hcF37HKkEiyZiBBejp23bhr6ecRqQ1Gp8xekbpbxz0WUWQ5f5XK4JEiek+62zl8KqNxFHXWJmVwF/Zx5tganRUtjSAa9ga/gGGVb2Ysl9kBIxCoSR1BQcIte4Lx9f7nVV5LvSyjYCq1sdOJklj3hPgebbNGH/NM1ID219ZUzKU6eE62sOAACh0JuKRSnBZgDOMQ7cEYq4W8kU6PA7TrCMyWAF5o11nR+GrEI7oaHw3e6uwVF2KeqXy0X6y/Q54snJY98szQiuHwI2OBE2ydtgCThd9M6K9sR62BkUaVtrnFLPx5Y6WsePcdKrEA=

addons:
  apt:
    packages:
      ant

before_script:
- git clone -b feature/makewar https://${GITHUB_USER}:${GITHUB_PASS}@github.com/departement-loire-atlantique/jPlatformBuild.git
- cd ./jPlatformBuild/tools/jalios

script:
- ant makeWarSocle
- cp -R ../dist ${TRAVIS_BUILD_DIR}
- cd ${TRAVIS_BUILD_DIR}
- export CODE_VERSION=`git describe`
- mv ${TRAVIS_BUILD_DIR}/dist/socle.war ${TRAVIS_BUILD_DIR}/dist/socle-${CODE_VERSION}.war

deploy:
  provider: releases
  api_key:
    secure: yM32cnzmoDafDRn1uj6JXznDirwqv6Dbyn3avIcrNmtMA3v2uEZHKSpJOb0zZ5TbPtWBs55ogFa0MXF+FMOlBOJ01HLaPjlhZQuebK2ljv0RIxU5he06rD/u0d3jl2876gz4gOR1BiW3v/7CB0lm9PuLv5wReQJnSfOuTXYILyISaiCxG+gvSkLQ7RMxb4Tz6hfxYpvXfq4MuUnMmNQrtdgh2EXR1YL81R9+lw6Wox38vb1IKE8iRE3dcXpG8Zf8VqclGu6ujViLt9iaNS2HTE/prP03NCZKMZLG07exkfHakIxkzHt7I3V55KhUO9t//s/uhCAZJ+AVg1QDjOzM7UYslATax9KjCdQK/iRo5Spko5MVXU00oVsrWpJSMekzkxd3BA1BC0evZ3HIkrdAVVTQq8oq6M9yfKa7roTes2HFBgAD1QZAZZRNhbkQ3rGcLkudvbhVpAIJ2OiAwTd5UP0xry5/SD9odz4AOm/BAe1GEB07XpdnRrQLVQOniX8g0g3NqmaJaS8ksnkORRKFpk38qfs7lLlEQzOFnEu0GZHFrs9sw7kkdsmzHzL8VvDioFbfQCJ73+2KqwmLYydWyvOyiiI6veXYxdcMYLMlMz7Vuuif5ZXtO3NVRhG6Rx05lES+vvbyoVtvJSapcCnJ58qUcO0UlzE1scBmA/d7qZI=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.war"
  skip_cleanup: true
  on:
    tags: true
