env:
  global:
  - secure: M/RT26ubxsP1EiJfb8hYHj/QOwa/MP8E86H1ifSORlFiy51Zp/2XadqdgsPQpNhwncnJuPcqWt4LvCXPm7NNfObqFyvmyhsB3Q7Ulk7prDjtJNw8+ARYnEM1n54FcR2FwWzs8hUJ0oS7d+Xu65KWz6bYRWKiPSXHqiREpNfYQnzGXEX1bg9JdXBeQTuOw6jJ4mZt0ab2FwKv4wG/S40s9uBEg8PIvJDsuGBfA3kGXj8MDpU1WX7YwPIXTzkpyWFe6P5V/gIfNDyFg+D0/gaFfma9NCCuvcsBV3TY9iFDUmIjL3OMLCCfbNVt2zYlT9S07e66RAxw4+yJnQ+RM21bM1IgEsu6qjp+eDsQdVPprV73sDY4msfBjIRCTxH8rm4G+WAK1GyRqnysWkGPpwwttfNMkxwnHIL1ZAfeYvd73y1hfNv0TTurjeuxQGWqi7ff3Jt1P56h2heat5C1iC3mwO7nrbMG1+dy0tOtsGckokTSUFnm8HlYo0wzlxYHg/zBpA+UTZkUkbk9zJdlcrcrzu1DODstvAZpqui6LQzS/c5mWWHGafGqmasDLwt/Qi/4bHxI7OTxA6D6MSnJQF5XhMiNw10HIbHQXHvQBFwcnJdYmCo62g+9RjCS+pEr/zVVZpL88ruDZ1cs4XONwXK10sq3DI54qQZn+jSRHGfzrk0=
  - secure: NUJbQvG+XWTnPUUl63YAVydtUKERKle3iQf2LgmVWeFH5C+KQL70itBNac5ofU5h9VaW1HfBKz/UdgCaoqsjTBSh8jDXB+e4o5NubOveTQanTAZOeyPopPa2jwGEAQASJNv2acL69TMyInrxkvRwHQLwVpRRgK2/C/IY2jhJ1S8fVKNRBv+cLXIAxlnBYnC2AdkhMycAR/DvMFbYf1R3ZpMyOc80pKFEU3RXat4bkOceun8GtvAK8Cqyq9iVroHRGwhYTmKHy/BJh72jWrTN3v2SfkTsWfCJwIQGPZ6ghjUXbxv9Hy37Sbtepj23cZIQ//2kCzjsG+yEClVvAtvL2obhZvsiHXqW2DEs/3u6q6Oh64TBu5z79RYzpKuKM7XWsYLe/0vT/B0ut1lLOHJg6QfEnd5j/kFy3lTWfIEH1g9zqwYe9Uz0qVN8imG75umFdmSHYSg6LtueixlkXQI8x6zAknc9/XHte7WK3id9B2F+X62Sko7iqrWUFdAwma205wUcjshBEAzd5ZlGrMBM2ljrOvHyZP5GAghq1PskDmCE3Xfps9hyD8V/9y+BTvYJO+gG1ug+TxKJREDzQz3syNWX002FA6wUsh4FoTwpc9o+uBmU/+Pq3EGCos+K2WapAiVwHsHdALZ3c1+Nz3PBZskQY8XAlsOWkpUjfV8aGLA=

addons:
  apt:
    packages:
      ant

before_script:
- git clone -b feature/makewar https://${GITHUB_USER}:${GITHUB_PASS}@github.com/departement-loire-atlantique/jPlatformBuild.git
- cd ./jPlatformBuild/tools/jalios

script:
- ant makeWarSocle
- cp -R ../dist ${TRAVIS_BUILD_DIR}
- cd ${TRAVIS_BUILD_DIR}
- export CODE_VERSION=`git describe`
- mv ${TRAVIS_BUILD_DIR}/dist/socle.war ${TRAVIS_BUILD_DIR}/dist/socle-${CODE_VERSION}.war

deploy:
  provider: releases
  api_key:
    secure: 1+S8fNLSidR7oFifFRNLKs1ONyv3abaWxxWg55CDHMguT+OORmmvpm1uv79MNmpGstjOSBsUt8LidgpD6yJ2twrCb2HKyNSYdp75QtGYMx4F5y7Qa2bXTx0qh71NNc7Ow62IN3rJxqa/XscaS9OSNMkrgkIvRc6LMttC5przLAJq6u1ixXQqKiWbjSdK289yz5KbWijBI1ZP5IN258IXvtkvlxVvP0i4X7nlVmz/zw9s//gl+vj0qIbM1txzidnTjXdVw2OPZhosSSFXiUHsC8IXkEJrFiLcKNlYCNrhttbQL18yjy1JbwdTSAzeorVvGQyUny+UvK7A2SwXXo3rI3+kSSvRsV7zAalELd+HfyBYXsB+83RV2ElhH/KX0yNqVFpLf3oGDEpal5KCRJjZaag/wkFBRqACOPXHIdfx0lkx7E3Bz7DcPrM3IlsdlW065coM1p7MojC+kg+/qy3MpqnCEgkXv1HpVA4mXHJsWINSeBigcHT/vJTXE3O3P85keI++Hx6QXmj5sPmOXsigj6UYVrlUbbiqcUFzRNQLBZGr/pqbkQbhQV+7lLssjVnRl9MoWzh/4CL3NtVlhXGrlc6aqTfr3joA6lMXLJmcIH6TRfbTf198sfagvnqYgc0INDavcs1dbUFkNy2gV/ETNXlC+3rh7dYUwJ2xsMgisWU=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.war"
  skip_cleanup: true
  on:
    tags: true
