env:
  global:
  - secure: M/RT26ubxsP1EiJfb8hYHj/QOwa/MP8E86H1ifSORlFiy51Zp/2XadqdgsPQpNhwncnJuPcqWt4LvCXPm7NNfObqFyvmyhsB3Q7Ulk7prDjtJNw8+ARYnEM1n54FcR2FwWzs8hUJ0oS7d+Xu65KWz6bYRWKiPSXHqiREpNfYQnzGXEX1bg9JdXBeQTuOw6jJ4mZt0ab2FwKv4wG/S40s9uBEg8PIvJDsuGBfA3kGXj8MDpU1WX7YwPIXTzkpyWFe6P5V/gIfNDyFg+D0/gaFfma9NCCuvcsBV3TY9iFDUmIjL3OMLCCfbNVt2zYlT9S07e66RAxw4+yJnQ+RM21bM1IgEsu6qjp+eDsQdVPprV73sDY4msfBjIRCTxH8rm4G+WAK1GyRqnysWkGPpwwttfNMkxwnHIL1ZAfeYvd73y1hfNv0TTurjeuxQGWqi7ff3Jt1P56h2heat5C1iC3mwO7nrbMG1+dy0tOtsGckokTSUFnm8HlYo0wzlxYHg/zBpA+UTZkUkbk9zJdlcrcrzu1DODstvAZpqui6LQzS/c5mWWHGafGqmasDLwt/Qi/4bHxI7OTxA6D6MSnJQF5XhMiNw10HIbHQXHvQBFwcnJdYmCo62g+9RjCS+pEr/zVVZpL88ruDZ1cs4XONwXK10sq3DI54qQZn+jSRHGfzrk0=
  - secure: mjpUXutxGeeXXJlSImet/1kTmLvpUnZaGn5ZowtgbGGEqUcsD3PMdpByjlzR4+gnz0xHwiBsJnZ9E5SFxBsLRx2kDMH6mtgSD2XFpXednM4MiNpII50icTct3rQ+5+Vl+nkitOO7C3/4CGVlDMnZAe0CPak/FKPYH4Q2K93l1Ncq1imqCtotHBZR/+z7XPU1Y+Z/5+QMP19cf5QCcLQRvVm0G5Liom/GDQJ8lukUMjutIpTGtpWZd9Z/ENUaUhp+A7UU3TK6DH70onStQxjLZ8RovNLuoO8/V7ag/AsAEQsIikCmj7w8WjNXRZsR0p+Uf2F4crswaLecPcRt9P/3EwTlIIRg9UinsbNaBcu2878P5O27hcF37HKkEiyZiBBejp23bhr6ecRqQ1Gp8xekbpbxz0WUWQ5f5XK4JEiek+62zl8KqNxFHXWJmVwF/Zx5tganRUtjSAa9ga/gGGVb2Ysl9kBIxCoSR1BQcIte4Lx9f7nVV5LvSyjYCq1sdOJklj3hPgebbNGH/NM1ID219ZUzKU6eE62sOAACh0JuKRSnBZgDOMQ7cEYq4W8kU6PA7TrCMyWAF5o11nR+GrEI7oaHw3e6uwVF2KeqXy0X6y/Q54snJY98szQiuHwI2OBE2ydtgCThd9M6K9sR62BkUaVtrnFLPx5Y6WsePcdKrEA=

addons:
  apt:
    packages:
      ant

before_script:
- git clone -b feature/makewar https://${GITHUB_USER}:${GITHUB_PASS}@github.com/departement-loire-atlantique/jPlatformBuild.git
- cd ./jPlatformBuild/tools/jalios

script:
- ant makeWarSocle
- cp -R ../dist ${TRAVIS_BUILD_DIR}
- cd ${TRAVIS_BUILD_DIR}
- export CODE_VERSION=`git describe`
- mv ${TRAVIS_BUILD_DIR}/dist/socle.war ${TRAVIS_BUILD_DIR}/dist/socle-${CODE_VERSION}.war

deploy:
  provider: releases
  api_key:
    secure: 1+S8fNLSidR7oFifFRNLKs1ONyv3abaWxxWg55CDHMguT+OORmmvpm1uv79MNmpGstjOSBsUt8LidgpD6yJ2twrCb2HKyNSYdp75QtGYMx4F5y7Qa2bXTx0qh71NNc7Ow62IN3rJxqa/XscaS9OSNMkrgkIvRc6LMttC5przLAJq6u1ixXQqKiWbjSdK289yz5KbWijBI1ZP5IN258IXvtkvlxVvP0i4X7nlVmz/zw9s//gl+vj0qIbM1txzidnTjXdVw2OPZhosSSFXiUHsC8IXkEJrFiLcKNlYCNrhttbQL18yjy1JbwdTSAzeorVvGQyUny+UvK7A2SwXXo3rI3+kSSvRsV7zAalELd+HfyBYXsB+83RV2ElhH/KX0yNqVFpLf3oGDEpal5KCRJjZaag/wkFBRqACOPXHIdfx0lkx7E3Bz7DcPrM3IlsdlW065coM1p7MojC+kg+/qy3MpqnCEgkXv1HpVA4mXHJsWINSeBigcHT/vJTXE3O3P85keI++Hx6QXmj5sPmOXsigj6UYVrlUbbiqcUFzRNQLBZGr/pqbkQbhQV+7lLssjVnRl9MoWzh/4CL3NtVlhXGrlc6aqTfr3joA6lMXLJmcIH6TRfbTf198sfagvnqYgc0INDavcs1dbUFkNy2gV/ETNXlC+3rh7dYUwJ2xsMgisWU=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.war"
  skip_cleanup: true
  on:
    tags: true
